project_id = "kykcanyioyzqctagrhud"

[functions.send-telegram-notification]
verify_jwt = false

[functions.check-notifications]
verify_jwt = false

[functions.test-notifications]
verify_jwt = false

[functions.fetch-odds]
verify_jwt = true
