project_id = "olmkgsvzpvyherlvokmz"

[functions.admin-delete-user]
verify_jwt = false

[functions.check-notifications]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false