export const SPORT_MARKETS = {
  calcio: [
    "1 Calcio",
    "X Calcio",
    "2 Calcio",
    "1X Calcio",
    "12 Calcio",
    "X2 Calcio",
    "Pari Calcio",
    "Dispari Calcio",
    "Goal Calcio",
    "No Goal Calcio",
    "Over 0.5 Calcio",
    "Over 1.5 Calcio",
    "Over 2.5 Calcio",
    "Over 3.5 Calcio",
    "Over 4.5 Calcio",
    "Under 0.5 Calcio",
    "Under 1.5 Calcio",
    "Under 2.5 Calcio",
    "Under 3.5 Calcio",
    "Under 4.5 Calcio",
    "Altro Calcio",
    "0 - 0 Calcio",
    "0 - 1 Calcio",
    "0 - 2 Calcio",
    "1 - 1 Calcio",
    "1 - 2 Calcio",
    "2 - 1 Calcio",
    "2 - 2 Calcio",
    "3 - 1 Calcio",
    "3 - 2 Calcio",
    "3 - 3 Calcio",
  ],
  tennis: ["Tennis 1", "Tennis 2", "Altro Tennis"],
  basket: ["Basket 1", "Basket 2", "Altro Basket"],
} as const;

export const CASINO_MARKETS = [
  "Rosso Casinò",
  "Nero Casinò",
  "Verde Casinò",
  "Colonna 1 Casinò",
  "Colonna 2 Casinò",
  "Colonna 3 Casinò",
  "Giocatore Casinò",
  "Banco Casinò",
  "Altro Casinò",
  "Slot Casinò",
  "Blackjack Casinò",
  "Quick Games Casinò",
  "Gratta & Vinci Casinò",
  "Bingo Casinò",
] as const;

export const QUICK_BET_METHODS = [
  "Baccarat",
  "Poker",
  "Bingo",
  "Blackjack",
  "Casino Live",
  "Gratta & Vinci",
  "Quick Games",
  "Roulette",
  "Slot Machine",
  "Sport",
  "Trading",
  "Altro",
] as const;

export const COMPETITIONS = [
  "Africa Cup of Nations",
  "Amichevoli internazionali",
  "Brasileirão",
  "Bundesliga (Germania)",
  "Copa del Rey (Spagna)",
  "Coppa Italia",
  "Coupe de France",
  "DFB-Pokal (Germania)",
  "Eredivisie (Olanda)",
  "FA Cup (Inghilterra)",
  "FIFA World Cup",
  "La Liga (Spagna)",
  "Liga MX (Messico)",
  "Ligue 1 (Francia)",
  "MLS (USA)",
  "Play-off Mondiali",
  "Premier League (Inghilterra)",
  "Primeira Liga (Portogallo)",
  "Qualificazioni Mondiali 2026",
  "Serie A (Italia)",
  "Supercoppe nazionali",
  "UEFA Champions League",
  "UEFA Conference League",
  "UEFA Europa League",
  "Altro",
] as const;

// Flatten all sport markets for easy access
export const ALL_SPORT_MARKETS = [
  ...SPORT_MARKETS.calcio,
  ...SPORT_MARKETS.tennis,
  ...SPORT_MARKETS.basket,
] as const;
